# Copyright 2026 Team SOBITS
# SPDX-License-Identifier: BSD-3-Clause
"""
Generate the RViz2 config a robot's views file describes.

RViz arranges nothing by itself: a fresh config shows an empty grid. This
writes a `.rviz` to open once, so every robot starts with the same displays —
the model, TF tree and laser scans in 3D, one Image display per camera, and
odometry for the base.

The cameras, lidars and frames come from the robot's `<robot>.robot.yaml`,
which sobits_robot_descriptor resolves. Run it after changing either file:

    ros2 run sobits_viz_rviz make_config --params config/<robot>/<robot>.yaml
"""

import argparse
from pathlib import Path
import re

from sobits_viz_rviz.robot_views import (
    cameras,
    find_descriptor,
    lidars,
    load_descriptor,
    load_params,
    tf_frames,
)
import yaml

HEIGHT = 1000
WIDTH = 1800
LEFT_DOCK_PX = 360
RIGHT_DOCK_PX = 480
MIN_IMAGE_PX = 200
TREE_HEIGHT = 600
BOTTOM_DOCK_PX = 80
BOTTOM_PANELS = ('Time',)

_HEADER = (
    '# Generated by sobits_viz_rviz make_config; do not edit by hand.\n'
    '# Regenerate: ros2 run sobits_viz_rviz make_config --params <robot>.yaml\n'
)


def _rgb(color: list) -> str:
    red, green, blue = (color + [255, 255, 255])[:3]
    return f'{red}; {green}; {blue}'


def _reliable_topic(topic: str, durability: str = 'Volatile') -> dict:
    return {
        'Value': topic,
        'Depth': 5,
        'History Policy': 'Keep Last',
        'Reliability Policy': 'Reliable',
        'Durability Policy': durability,
    }


def _best_effort_topic(topic: str) -> dict:
    return {
        'Value': topic,
        'Depth': 5,
        'History Policy': 'Keep Last',
        'Reliability Policy': 'Best Effort',
        'Durability Policy': 'Volatile',
    }


def _grid_display() -> dict:
    return {
        'Class': 'rviz_default_plugins/Grid',
        'Name': 'Grid',
        'Enabled': True,
        'Value': True,
        'Alpha': 0.5,
        'Cell Size': 1,
        'Color': '160; 160; 164',
        'Plane': 'XY',
        'Plane Cell Count': 10,
        'Reference Frame': '<Fixed Frame>',
    }


def _robot_model_display(robot, scene: dict, prefix: str) -> dict:
    topic = robot.topic(scene.get('description_topic', 'robot_description'))
    return {
        'Class': 'rviz_default_plugins/RobotModel',
        'Name': 'RobotModel',
        'Enabled': True,
        'Value': True,
        'Visual Enabled': True,
        'Collision Enabled': scene.get('show_collision', False),
        'Alpha': 1,
        'Description Source': 'Topic',
        'Description File': '',
        'Description Topic': _reliable_topic(topic, durability='Transient Local'),
        'TF Prefix': prefix,
        'Update Interval': 0,
    }


def _tf_display(tf: dict, prefix: str, frames: list) -> dict:
    # Both filters are a single regex, so the frames become one alternation.
    def framed(key, default=None):
        names = [re.escape(prefix + f) for f in (tf.get(key, default) or [])]
        return '^(' + '|'.join(names) + ')$' if names else ''

    shown = bool(tf.get('enable'))
    return {
        'Class': 'rviz_default_plugins/TF',
        'Name': tf.get('name', 'TF'),
        'Enabled': shown,
        'Value': shown,
        'Frame Timeout': 15,
        'Marker Scale': float(tf.get('axis_scale', 0.4)),
        'Show Arrows': False,
        'Show Axes': True,
        'Show Names': bool(tf.get('label', False)),
        'Update Interval': 0,
        'Filter (whitelist)': framed('frames', frames),
        'Filter (blacklist)': framed('exclude'),
    }


def _image_display(name: str, topic: str, depth_range=None) -> dict:
    # A depth image is mostly infinity where nothing is in range, so
    # normalising it spreads noise over the whole greyscale.
    low, high = (depth_range or [0.0, 0.0])[:2]
    ranged = high > low
    return {
        'Class': 'rviz_default_plugins/Image',
        'Name': name,
        'Enabled': True,
        'Value': True,
        'Normalize Range': not ranged,
        'Min Value': float(low) if ranged else 0,
        'Max Value': float(high) if ranged else 1,
        'Median window': 5,
        'Topic': _best_effort_topic(topic),
    }


def _point_cloud_display(name: str, topic: str, points: dict) -> dict:
    # depth_image_proc emits bare xyz, so colouring by intensity fails; height
    # needs no channel.
    colour = points.get('color')
    shown = bool(points.get('enable'))
    return {
        'Class': 'rviz_default_plugins/PointCloud2',
        'Name': name,
        'Enabled': shown,
        'Value': shown,
        'Alpha': 1,
        'Axis': 'Z',
        'Color': _rgb(colour or [255, 255, 255]),
        'Color Transformer': 'FlatColor' if colour else 'AxisColor',
        'Decay Time': 0,
        'Position Transformer': 'XYZ',
        'Selectable': True,
        'Size (Pixels)': points.get('size_px', 2.0),
        'Size (m)': 0.01,
        'Style': 'Points',
        'Use Fixed Frame': True,
        'Use rainbow': True,
        'Topic': _best_effort_topic(topic),
    }


def _laser_scan_display(name: str, topic: str, view: dict) -> dict:
    shown = bool(view.get('scan', True))
    return {
        'Class': 'rviz_default_plugins/LaserScan',
        'Name': name,
        'Enabled': shown,
        'Value': shown,
        'Alpha': 1,
        'Color': _rgb(view.get('color') or [255, 255, 255]),
        'Color Transformer': 'FlatColor',
        'Decay Time': 0,
        'Position Transformer': 'XYZ',
        'Selectable': True,
        'Size (Pixels)': view.get('point_size_px', 3.0),
        'Size (m)': 0.01,
        'Style': 'Points',
        'Use Fixed Frame': True,
        'Use rainbow': True,
        'Topic': _reliable_topic(topic),
    }


def _odometry_display(name: str, topic: str) -> dict:
    return {
        'Class': 'rviz_default_plugins/Odometry',
        'Name': name,
        'Enabled': True,
        'Value': True,
        'Angle Tolerance': 0.1,
        'Position Tolerance': 0.1,
        'Keep': 100,
        'Shape': {'Value': 'Arrow'},
        'Topic': _reliable_topic(topic),
    }


def _displays(robot, views: dict, prefix: str) -> list:
    scene = views.get('scene') or {}
    displays = []

    if scene.get('grid', True):
        displays.append(_grid_display())
    if scene.get('urdf', True):
        displays.append(_robot_model_display(robot, scene, prefix.rstrip('/')))
    # Listed whatever `enable` says, so the frames are one click away.
    displays.append(_tf_display(views.get('tf') or {}, prefix, tf_frames(robot)))

    # Listed whatever `scan` says, so a scan is one click away.
    for name, entry, view in lidars(robot, views.get('lidars') or {}):
        displays.append(_laser_scan_display(name, entry['scan_topic'], view))

    for name, label, entry, view in cameras(robot, views.get('cameras') or {}):
        compressed = view.get('use_compressed', not entry.get('is_depth'))
        topic = entry.get('compressed_topic') if compressed else entry.get('raw_topic')
        depth_range = view.get('range_m', entry['range_m']) if entry['is_depth'] else None
        displays.append(_image_display(label, topic, depth_range))
        # Listed whatever `enable` says, so the cloud is one click away.
        if entry.get('points_topic'):
            points = view.get('points') or {}
            cloud = points.get('name', f'{label} points')
            displays.append(
                _point_cloud_display(cloud, entry['points_topic'], points))

    base = views.get('base') or {}
    mobile = robot.mobile_base
    if base.get('enable', True) and mobile and mobile.odom_topic:
        displays.append(
            _odometry_display(base.get('name', 'Base'), robot.topic(mobile.odom_topic)))

    return displays


def _panels() -> list:
    # Help Height 0 drops the description box under the display tree.
    return [
        {'Class': 'rviz_common/Displays', 'Name': 'Displays', 'Help Height': 0,
         'Tree Height': TREE_HEIGHT},
        {'Class': 'rviz_common/Views', 'Name': 'Views'},
        {'Class': 'rviz_common/Time', 'Name': 'Time'},
    ]


def _tools() -> list:
    return [
        {'Class': 'rviz_default_plugins/Interact'},
        {'Class': 'rviz_default_plugins/MoveCamera'},
        {'Class': 'rviz_default_plugins/Select'},
        {'Class': 'rviz_default_plugins/FocusCamera'},
        {'Class': 'rviz_default_plugins/Measure'},
        {'Class': 'rviz_default_plugins/SetInitialPose'},
        {'Class': 'rviz_default_plugins/SetGoal'},
        {'Class': 'rviz_default_plugins/PublishPoint'},
    ]


def _views(scene: dict, fixed_frame: str) -> dict:
    return {
        'Current': {
            'Class': 'rviz_default_plugins/Orbit',
            'Name': 'Current View',
            'Value': 'Orbit (rviz_default_plugins)',
            'Distance': float(scene.get('camera_distance_m', 4.0)),
            'Pitch': 0.5,
            'Yaw': 0.5,
            'Focal Point': {'X': 0, 'Y': 0, 'Z': float(scene.get('camera_height_m', 0.6))},
            'Target Frame': fixed_frame,
        },
        'Saved': None,
    }


def _dock_state(left: list, right: list, bottom: list) -> str:
    """Return the Qt dock layout as RViz stores it, or '' without Qt."""
    # QMainWindow's state is a binary Qt format, so Qt itself writes it.
    try:
        from PyQt5.QtCore import Qt
        from PyQt5.QtWidgets import QApplication, QDockWidget, QMainWindow, QWidget
    except ImportError:
        return ''

    app = QApplication.instance() or QApplication(['rviz-layout', '-platform', 'offscreen'])
    window = QMainWindow()
    window.resize(WIDTH, HEIGHT)
    window.setCentralWidget(QWidget())

    def docked(names, area):
        widgets = []
        for name in names:
            dock = QDockWidget(name, window)
            dock.setObjectName(name)
            dock.setWidget(QWidget())
            window.addDockWidget(area, dock)
            widgets.append(dock)
        for above, below in zip(widgets, widgets[1:]):
            window.splitDockWidget(above, below, Qt.Vertical)
        return widgets

    panels = docked(left, Qt.LeftDockWidgetArea)
    images = docked(right, Qt.RightDockWidgetArea)
    strip = docked(bottom, Qt.BottomDockWidgetArea)
    if panels:
        window.resizeDocks(panels, [LEFT_DOCK_PX] * len(panels), Qt.Horizontal)
    if images:
        window.resizeDocks(images, [RIGHT_DOCK_PX] * len(images), Qt.Horizontal)
        share = max(MIN_IMAGE_PX, HEIGHT // len(images))
        window.resizeDocks(images, [share] * len(images), Qt.Vertical)
    if strip:
        window.resizeDocks(strip, [BOTTOM_DOCK_PX] * len(strip), Qt.Vertical)
    state = bytes(window.saveState().toHex()).decode()
    del app
    return state


def _window(displays: list) -> dict:
    """Size the window and dock the image panels down the right-hand side."""
    names = [panel['Name'] for panel in _panels()]
    panels = [name for name in names if name not in BOTTOM_PANELS]
    strip = [name for name in names if name in BOTTOM_PANELS]
    images = [d['Name'] for d in displays if d['Class'].endswith('/Image')]
    geometry = {'Height': HEIGHT, 'Width': WIDTH, 'X': 60, 'Y': 30,
                'Hide Left Dock': False, 'Hide Right Dock': not images}
    for name in names + images:
        geometry[name] = {'collapsed': False}
    state = _dock_state(panels, images, strip)
    if state:
        geometry['QMainWindow State'] = state
    return geometry


def build(params: dict, descriptor) -> dict:
    """Return the RViz2 config for this robot as a YAML-ready dict."""
    robot = load_descriptor(descriptor)
    views = params.get('views') or {}
    scene = views.get('scene') or {}
    prefix = params.get('frame_prefix', '')
    fixed_frame = prefix + scene.get('fixed_frame', robot.odom_frame)

    config = {'Panels': _panels()}
    displays = _displays(robot, views, prefix) if scene.get('enable', True) else []
    if scene.get('enable', True):
        config['Visualization Manager'] = {
            'Class': '',
            'Displays': displays,
            'Enabled': True,
            'Global Options': {
                'Background Color': '48; 48; 48',
                'Fixed Frame': fixed_frame,
                'Frame Rate': 30,
            },
            'Name': 'root',
            'Tools': _tools(),
            'Transformation': {'Current': {'Class': 'rviz_default_plugins/TF'}},
            'Value': True,
            'Views': _views(scene, fixed_frame),
        }
        config['Window Geometry'] = _window(displays)
    return config


def main() -> None:
    """Write the RViz2 config of the robot the parameter file describes."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--params', type=Path, required=True,
        help="the robot's parameter file, config/<robot>/<robot>.yaml")
    parser.add_argument(
        '--descriptor', type=Path,
        help='the <robot>.robot.yaml; defaults to the one sobits_robot_descriptor '
             'resolves for <app_id>, as the launch file does')
    parser.add_argument(
        '--output', type=Path,
        help='defaults to <app_id>.rviz next to the parameter file')
    args = parser.parse_args()

    params = load_params(args.params)
    if not args.descriptor and not params.get('app_id'):
        raise SystemExit(f'{args.params} has no app_id; pass the robot with --descriptor')
    descriptor = args.descriptor or find_descriptor(params['app_id'])
    app_id = params.get('app_id') or load_descriptor(descriptor).robot_id
    output = args.output or args.params.resolve().parent / f'{app_id}.rviz'

    output.parent.mkdir(parents=True, exist_ok=True)
    config = build(params, descriptor)
    text = yaml.safe_dump(config, default_flow_style=False, sort_keys=False)
    output.write_text(_HEADER + text)
    count = len(config.get('Visualization Manager', {}).get('Displays', []))
    print(f'wrote {output} ({count} displays)')


if __name__ == '__main__':
    main()
